### ISSUE TITLE
Large File Uploading Error

### ISSUE THREAD

**Issue by InfernalPlank** [0xHaru/Nerd-Storage#1]
Writing this as an open-ended discussion and will be submitting the same information to the respective packages involved in this issue. Please note that this issue has been raised *several times* before, but has yet to be fixed / resolved. ([Flask #2086](https://github.com/pallets/flask/issues/2086), [Werkzeug #1041](https://github.com/pallets/werkzeug/issues/1041), [Werkzeug #510](https://github.com/pallets/werkzeug/issues/510), [Codalab-Worksheet #301](https://github.com/codalab/codalab-worksheets/issues/301), see also: [StackOverflow Question](https://stackoverflow.com/questions/28321690/python3-flask-upload-file-in-server-memory))

Currently, the [`default_stream_factory` ](https://github.com/pallets/werkzeug/blob/eff04478a83619b4d7f15e6eee16a99bd80ed879/src/werkzeug/formparser.py#L60) that is embedded in [Werkzeug](https://github.com/pallets/werkzeug) (a [Flask](https://github.com/pallets/flask) Dependency) splits files and performs one of two operations:

- If under 500kb, store the uploaded file in-memory.
- If over 500kb, store the file in a temp file in /tmp.

This creates one main *visible* problem:

- Machines with a smaller /tmp may send a traceback to the user with a "No Space on Device" OSError, not allowing uploads to complete.

And one *hidden* problem:

- Large File Uploads (>500kb as defined in [`default_stream_factory`](https://github.com/pallets/werkzeug/blob/eff04478a83619b4d7f15e6eee16a99bd80ed879/src/werkzeug/formparser.py#L66)) *still* eat into the RAM of the host machine, despite being sent to /tmp via [`TemporaryFile`](https://github.com/pallets/werkzeug/blob/eff04478a83619b4d7f15e6eee16a99bd80ed879/src/werkzeug/formparser.py#L71) or [`SpooledTemporaryFile`](https://github.com/pallets/werkzeug/blob/eff04478a83619b4d7f15e6eee16a99bd80ed879/src/werkzeug/formparser.py#L69).

This redundancy can lead to a severe issue.
I was testing NS on a 4GB machine and performing a 4GB upload, which crashed the machine, and led me do two things:

- Up my /tmp size to 10GB in `/etc/fstab`
- Investigate the Memory Leak

I've not found a fix for this or any surefire way of counteracting the problem. Despite ensuring that /tmp has more than enough storage, RAM is still consumed. If the upload eats the RAM to 100% a system crash will occur, throwing the server offline. Somewhere in the reading I've been doing it's been suggested that Werkzeug stores the files into memory regardless of size (rendering `formparser` useless?) and has sloppy management with the data.

Any possible fixes or monkey patches would be appreciated; collaboration and discussion is welcome!

**Comment by 0xHaru** [comment]
Thank you for reporting the issue and for your attention to detail. I will try to recreate the bug and fix it.
Specifically, I'd like to figure out which line of code in NS throws the error to decide if a third party library should be modified or not.

**Comment by InfernalPlank** [comment]
@0xHaru The traceback on OSError for "No Space on Device" can be fixed by resizing /tmp appropriately, and is served by Flask itself (if I'm not mistaken).

The main issue is the memory leak causing the server to crash, which does indeed appear to stem from a third-party library (yes, [Werkzeug](https://github.com/pallets/werkzeug), we're looking at you).

edit: I have posted this as an issue in the Flask and Werkzeug repositories respectively, but only Werkzeug kept my issue open. Flask declined the issue, as it stems from Werkzeug, not Flask itself. That issue can be viewed at any time ([Werkzeug #2166](https://github.com/pallets/werkzeug/issues/2166)).

edit 2: I have made a potential discovery / fix, but have yet to test it so it remains entirely theoretical. If the content is `application/multipart-formdata`, it seems `formparser` is used regardless, so if we were to change the content's mimetype and read it in through the `.stream()` passing chunks through a `while not stream.is_exhausted` loop, effectively streaming the data "through" memory but not storing it there permanently. Let me know if this is something we should investigate further. If so, I can attempt a fix and open a PR.

**Comment by 0xHaru** [comment]
@RHQ-Rusty could you please share your edit to /etc/fstab? I would like to add it to the README.

About the main problem, your solution is clever and I'm very interested in it, could you post some hints regarding how you found out that `formparser` is used regardless if the `enctype` is set to `application/multipart-formdata`?

Feel free to open a PR and thank you for helping out!

**Comment by InfernalPlank** [comment]
@0xHaru - Editing `/etc/fstab` can be done with Vim, Nano, GEdit, etc. but _must_ be run as **sudo**.

This is an example with nano: `sudo nano /etc/fstab`
Note: it may be slightly different on different machines, but the core concept is the same; look for `/tmp` or `tmpfs`

Each line in `/etc/fstab` follows this format: `<file system> <dir> <type> <options> <dump> <pass>`
You will find the line:
`tmpfs /tmp tmpfs defaults,noatime,mode=1777 0 0`
and append a `size=10G` after the `defaults`, making the new line:
`tmpfs /tmp tmpfs defaults,size=10G,noatime,mode=1777 0 0`
and Save and Close the file, then reboot the system.

As for the `formparser` and it's usage of the `default_stream_factory` and writing to memory regardless: I wasn't clear enough when I was explaining the error and that's my fault. What I was trying to convey is that, if `application/multipart-formdata` is the `enctype`, it overrides or somehow ignores the use of _any_ stream factory, _including_ `default_stream_factory` which means that, while files may be large enough to be stored in /tmp, and they may be stored in /tmp, they are _also_ getting streamed into memory. This is the unintended behavior / functionality that is causing server instability and crashing.

I will further investigate this and open a PR if I can find a monkey patch or even a semi-stable fix; let me know if you make any progress as well!

**Comment by mishka** [comment]
Hi @RHQ-Rusty ,

Could you please also provide logs of the failure so perhaps we could look into it better, all together?

**Comment by 0xHaru** [comment]
@RHQ-Rusty unfortunately I wasn't able to recreate the bug so I'm interested in the traceback too.

Could you also point to the source code (within Werkzeug) that led you to your potential solution? I would like to read it.

**Comment by InfernalPlank** [comment]
I will attempt to re-install the entirety of Nerd-Storage and the default dependencies and see if I can capture some photos or videos explaining the issue; it should be entirely reproducible.

@0xHaru - The Flask server doesn't send a traceback when memory hits 100% usage on the server, it simply crashes the _entire machine_ running the server, which needs to be rebooted before it can be used again. The source for Werkzeug has been linked in the original post / my comments: the most probably file causing the issues is `formparser.py` circa line 60 - but again, this has been linked to above. There may be other files in Werkzeug causing the issue as well, but `formparser` hosts the logic for determining if files get streamed to memory or written to a temporary file. My statement wasn't one of fact, but rather of suggestion: if I'm able to confirm that files are being streamed _both_ into _memory_ and a _temp file_, then the behavior is unintended, and problems will ensue. For me, I've been able to match these conditions locally, and can confirm something is overriding the determination of storing in RAM vs. streaming to a Tempfile, and is consistently crashing host machines.

@mishka - Logs to my system or from the Flask app?

**Comment by InfernalPlank** [comment]
@0xHaru @mishka I just confirmed reproducibility. If you can't meet the RAM requirement to experience the issue, consider virtualizing a new VM to experiment with. On a fresh machine (I'm using Arch, but it should be the same for most / all distros),

- `git clone https://github.com/0xHaru/Nerd-Storage`
- `cd Nerd-Storage/`
- `python -m virtualenv venv`
- `source venv/bin/activate`
- `pip install Flask Flask-Login Jinja2`
- `python src/NERD/hash/hash.py` --> fill out password; allow script to finish.
- `nano src/NERD/config.py` --> any text editor will work; change storage path and port (if required).
- `python setup.py install`

This will establish a working Nerd-Storage Virtual Environment. From here, run the server via `nerdstorage`.
Now, to experience the issue, you **must** make sure two conditions are met:

- Host Machine has Less RAM than Target File Upload (e.g. for 5GB upload, you can experience the issue with 4GB RAM)
- Host Machine with Large Enough /tmp (see my `/etc/fstab` edit above for guidance)

Now, start an upload larger than the viable amount of available RAM on the system, and run `bpytop` or `htop` or another system monitor. Additionally, in another command line instance, run `df -h`. You will notice that, as `/tmp` increases in size, the RAM usage of the Python process hosting Nerd-Storage increases it's RAM consumption in parallel. This is also apparent from the system monitor, where you can see the RAM steadily increasing in parallel with the transfer rate of the uploaded file.

Allow the upload to go as far as it can; once the RAM has been consumed to 100%, the host machine will crash.

If you would like a live video demonstration, simply ask, and I can either record something and upload it, or do a live demonstration via Discord or another screen-sharing application / website.

**Comment by 0xHaru** [comment]
@RHQ-Rusty thank you for the clarification and the step by step description to be able to recreate the problem. 
I created a new VM and did some testing and indeed the problem occurs exactly as you described, I will try to solve the problem and will inform you if I discover anything new.

Please let me know if you have any suggestions.

**Comment by InfernalPlank** [comment]
@0xHaru I've been doing DD on this since I raised the issue and it's looking like there are a few possible fixes:

- Rewrite Werkzeug to Effectively Stream Files or Properly Use `default_stream_factory()` in `formparser.py`
- Try to Implement [Flask-Uploads](https://github.com/maxcountryman/flask-uploads) (works in a modular form; similar to how Flask-Login works)
- Switch to [Django](https://github.com/django/django) (the issue doesn't exist there _to my knowledge_)

I've been trial-and-erroring with rewriting Werkzeug, and am running into some stalls and issues, but I think there is definitely a solution to this problem; we just have to find it.

edit: as a switch to Django means essentially a full rewrite to a new framework, I would recommend saving this suggestion as a last-resort.

**Comment by 0xHaru** [comment]
After giving it some thought I decided to opt for a client-side solution. The client uses [flow.js](https://github.com/flowjs/flow.js/) to split the file into chunks and send them independently. The server saves each chunk as a separate file, then once all the chunks have been received the server merges them together to recreate the original file.

This solution isn't very fast if hosted on a machine with limited resources but it works.

I also implemented a simple demo, to test it just download [fix.zip](https://github.com/0xHaru/Nerd-Storage/files/6729836/fix.zip) and run `app.py`. The only dependency is [Flask](https://pypi.org/project/Flask/).

**Comment by InfernalPlank** [comment]
@0xHaru - I reviewed the source and this is a surprisingly well-thought client-based approach for a fix! It works as intended and feels nice! Would you like to create and merge a PR implementing this into `master`, or do you want me to do it?

**Comment by 0xHaru** [comment]
Thank you for the positive feedback @RHQ-Rusty, it's always appreciated.

I actually have to fix a couple of minor mistakes here and there so I'm also gonna add this new functionality and create a new release.

**Comment by InfernalPlank** [comment]
@0xHaru any ETA on an updated release? Is there anything you need from myself or @mishka in terms of contributions?

**Comment by 0xHaru** [comment]
Hey @RHQ-Rusty, unfortunately I'm very busy these days so I can't give an accurate ETA of the next release. 

I have a very specific vision of how I want to integrate this new feature this is why I haven't asked for any contribution.

Having said that if you need this functionality asap I can develop and attach a pre-release in this thread.

**Comment by InfernalPlank** [comment]
@0xHaru - take your time! I'm excited to see this project come together. I'm not 100% sure of what all your plans are in the specific vision of how you want NS to end up, but I support this 100%. If you need me to do anything in terms of further contribution, just let me know, I'm eager to see this project come to life!

**Comment by 0xHaru** [comment]
Unfortunately I am still very busy but I think by the end of the month I will be able to publish the new release. 

Thank you for the support and for contributing @RHQ-Rusty, I really appreciate it!

**Comment by InfernalPlank** [comment]
> Unfortunately I am still very busy but I think by the end of the month I will be able to publish the new release.
> 
> Thank you for the support and for contributing @RHQ-Rusty, I really appreciate it!

Any ETA on an update RC or Release? :)

**Comment by 0xHaru** [comment]
@RHQ-Rusty I just published the new release.
Please let me know if this solution solves the problem so I can mark this issue as resolved.

**Comment by InfernalPlank** [comment]
@0xHaru - release looks good! I haven't encountered any issues so far but will continue to test; perhaps at some point (or I can do it if you're busy) a feature to determine system RAM and uploaded file size to automatically filter the handling of files between the splitting into chunks and the typical upload fashion. Looks and feels very polished, good release! :)

**Comment by 0xHaru** [comment]
Thank you @RHQ-Rusty, I appreciate your positive feedback!

I was also thinking about implementing something like that initially but I chose to handle things in a more modular way. 
I want to keep this project very simple and beginner-friendly and I want to use as little JavaScript as possible.

**Comment by InfernalPlank** [comment]
Unfortunately, with further testing, files > 50mb seem to stall and not work? This could be client-side as I haven't found a cause yet, but using the large file upload for anything > 50mb sends an error message to the upload page and then stops on the server side.

**Comment by 0xHaru** [comment]
Before publishing the release I tested the program on a 4gb machine and uploaded files of various sizes, from 1gb up to 5gb and never encountered this issue. I tested it again with a 1gb file and the upload went smoothly.

Maybe the problem is caused by something else?
